//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace AMS_v1._3.Models
{
    using System;
    using System.Collections.Generic;

    public partial class student
    {
        public int id { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Username")]
        public string username { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 4)]
        public string passwd { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Confirm Password")]
        [DataType(DataType.Password)]
        [NotMapped]
        [Compare("passwd", ErrorMessage = "The password and confirmation password do not match, Try Again!")]
        public string confirmpasswd { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "First Name")]
        public string firstname { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Middle Name")]
        public string middlename { get; set; }

        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "This field is required")]
        public string lastname { get; set; }

        [Display(Name = "Complete Address")]
        [Required(ErrorMessage = "This field is required")]
        public string addrss { get; set; }

        [Display(Name = "Phone Number")]
        [Required(ErrorMessage = "This field is required")]
        public string phonenum { get; set; }
        public int balance { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public string parentid { get; set; }

        public virtual parent parent { get; set; }
    }
}
